(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> 'fieldname'"
p3
sS'layer'
p4
S'/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f62b0aaa730, file "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/leonardo/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 206, in <module>\n  File "/home/leonardo/Downloads/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 180, in busca_aluno\n    \'matric_aluno\':request.vars.c_matricula\n  File "/home/leonardo/Downloads/web2py/gluon/sqlhtml.py", line 2030, in factory\n    return SQLFORM(DAL(None).define_table(table_name, *fields_with_clones), **attributes)\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/base.py", line 586, in define_table\n    table = self.lazy_define_table(tablename, *fields, **args)\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/base.py", line 598, in lazy_define_table\n    table = table_class(self, tablename, *fields, **args)\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/objects.py", line 313, in __init__\n    field[\'fieldname\'] not in fieldnames:\nKeyError: \'fieldname\'\n'
p11
s.