(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> 'Field' object is not callable"
p3
sS'layer'
p4
S'/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f23b504bc30, file "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 9>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/leonardo/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 226, in <module>\n  File "/home/leonardo/Downloads/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/leonardo/Downloads/web2py/gluon/tools.py", line 3982, in f\n    return action(*a, **b)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 172, in busca_aluno\n    filmes = db(db.cadastro.nome_crianca(\'%\'+request.vars.nome_kids+\'%\')).select().first()\nTypeError: \'Field\' object is not callable\n'
p11
s.